import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { listVersions } from "smart-contract-verifier";
import styles from "../styles/Home.module.css";
import Verify, { VerifyProps } from "../components/Verify";

interface HomeProps {
  solcVersions: string[];
}

const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const solcVersions = await listVersions();
  const hour = 60 * 60;
  return {
    props: {
      solcVersions,
    },
    revalidate: 24 * hour,
  };
};

const Home = ({ solcVersions }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Smart Contract Verifier</h1>

        <p className={styles.description}>
          Upload the smart contract file to be verified.
        </p>

        <div className={styles.grid}>
          <Verify solcVersions={solcVersions} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export { getStaticProps };
export default Home;
